version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bracketier
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_database

  api:
    build:
      context: ./api
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DATABASE: bracketier
      NODE_ENV: development
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    container_name: ts_api

  client:
    build:
      context: ./client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /app
    container_name: react_client

volumes:
  postgres_data: {}
  node_modules: {}
